### ISSUE TITLE
Draggable iPad Canvas Problem

### ISSUE THREAD

**Issue by nicelon** [ideo/avocado#4]
Hi, 

I have a issue using the draggable patch. I am basically unable to use the whole iPad Canvas with the draggable patch. I am using the newest the avocado 2, Origami and QC.

Short Video:
http://cl.ly/19303D343q23?_ga=1.134863416.813047996.1429190218

Not sure if its a bug or something on my end - would be great to get some help ;)

**Comment by trive** [comment]
You are right, my friend—apologies for the bug!
It's fixed now. Either download the updated installer or replace the Draggable Layer patch with the one you find here on GitHub.
