### ISSUE TITLE
Can prototype be used as foundation for an actual IOS app?

### ISSUE THREAD

**Issue by MartinOrtiz** [ideo/avocado#7]
Can I use or incorporate the fancy GUI or fancy effects in an actual IOS app?

I am mainly interested in making GUI components in Avocado, the rest of the stuff can be done in XCode/Swift project.

**Comment by trive** [comment]
There are some effects that can be translated from Quartz Composer to iOS native code.
Usually that requires using Pop Animations.
More info here: http://facebook.github.io/origami/documentation/concepts/CodeExport.html
