### ISSUE TITLE
Installer doesn't complete

### ISSUE THREAD

**Issue by csinco** [ideo/avocado#8]
I tried installing Avocado today on El Capitan.  It seems to be hanging on the part "Waiting for other installations to complete".  I have Origami and QC installed already, so not sure what is happening.

<img width="620" alt="screen shot 2015-10-19 at 1 07 31 am" src="https://cloud.githubusercontent.com/assets/4108456/10572509/f3dd1cd0-75fd-11e5-91f1-4adcb1cbc44b.png">

**Comment by trive** [comment]
El Captain is not supported yet.
What files do you see inside the two folders in  ~/Library/Graphics ?
Is this the first time you install Avocado?

**Comment by trive** [comment]
On my test machines it installs successfully.
Could you please let us know which version you're running?
Also, have you simply tried to restart the installation?

That message sounds like there are other installers running at the same time.
