### ISSUE TITLE
Carousel patch is broken

### ISSUE THREAD

**Issue by ajimix** [ideo/avocado#9]
It seems like carousel patch and controls are not working properly.

Find [here](https://db.tt/lNIgFP77) an example where you can try to press Next/Previous buttons and you'll see how it doesn't behave properly

Thanks :)

**Comment by trive** [comment]
Unfortunately I'm in a remote area (without my laptop) for the next few weeks.

I'll have a look as soon as I'm back.
Thank you for reporting.

**Comment by wmanderson** [comment]
Any update on this? I'm having a similar issue w/ the carousel controls patch. 

Either doesn't work, or tries to jump to the last index. Very sporadic

**Comment by trive** [comment]
If you are experiencing this issue please [email me](mailto:gtrive@gmail.com) a composition in which the patch is not working.
